### ISSUE TITLE
Issue with Cmake build

### ISSUE THREAD

**Issue by nateha11** [ORNL-MDF/3DThesis#27]
I have attempted to use to build example shown in the README file in VS Community. However, the build file does not result in the same format as described in the README file (i.e. build/application/3DThesis). Due to my lack of expertise in the modeling area, I have attempted to just follow the instructions, but I seem to be making an error somewhere.

[3DThesis Build Attempt.pptx](https://github.com/user-attachments/files/18154141/3DThesis.Build.Attempt.pptx)

**Comment by gknapp1** [comment]
The image you show on Slide 3 looks like Visual Studio is automatically building the CMake project correctly and outputting the `3DThesis` binary to `C:/Users/nhall/source/repos/3DThesis/out/build/x64-Debug`. Is there a working binary in that directory? Since you are building through Visual Studio, the build documentation is not directly applicable and you shouldn't need to run `cmake` from the terminal.

As for `Debug` versus `Release`, I recommend specifying `Release` for better performance.

**Comment by nateha11** [comment]
[cid:de275a30-56c6-47e0-aa4e-a78604070277]

There is no working binary in this build folder. In fact, nothing exists inside it.

________________________________

**Comment by streeve** [comment]
This is likely a real issue with the optional MPI. I'll need to look into it further.

**Comment by gknapp1** [comment]
Once merged, #28 should solve this problem. 

@nateha11, note that once Visual Studio recognizes the CMake project and generates the correct configuration, you still have to the green-triangular "run" button to generate the executable. You will get an error about not finding an input file when it attempts to run 3DThesis (unless you configure a specific debug command arguments), but you will be able to use "3DThesis.exe" file it generates outside of Visual Studio.

**Comment by streeve** [comment]
Reopen as needed
